#!/usr/bin/env python3
"""Convert camerasensors.csv into SdCameraSensors.cpp.

Reads camerasensors.csv from the same directory as this script and writes SdCameraSensors.cpp
for use in Shot Designer. The file is intended to be committed; re-run this script after
updating the CSV. SdCameraSensors.h is hand-coded and not touched by this script.
"""

import csv
from pathlib import Path

SCRIPT_DIR = Path(__file__).parent
CSV_PATH = SCRIPT_DIR / "camerasensors.csv"
CPP_PATH = SCRIPT_DIR / "SdCameraSensors.cpp"


def text_literal(s: str) -> str:
    return f'TEXT("{s}"),'


def main() -> None:
    with CSV_PATH.open(newline="", encoding="utf-8") as f:
        rows = list(csv.DictReader(f))

    mfr_w = max(len(text_literal(r["manufacturer"])) for r in rows)
    cam_w = max(len(text_literal(r["camera"])) for r in rows)
    fmt_w = max(len(text_literal(r["format"])) for r in rows)

    lines = []
    for r in rows:
        mfr = text_literal(r["manufacturer"]).ljust(mfr_w)
        cam = text_literal(r["camera"]).ljust(cam_w)
        fmt = text_literal(r["format"]).ljust(fmt_w)
        w = f'{float(r["width"]):6.2f}f'
        h = f'{float(r["height"]):6.2f}f'
        lines.append(f"        {{ {mfr} {cam} {fmt} FVector2D({w}, {h}) }},")

    cpp_contents = (
        "// Copyright Hollywood Camera Work\n"
        "// Generated by convert_to_cpp.py — do not edit by hand.\n"
        "\n"
        '#include "SdCameraSensors.h"\n'
        "\n"
        "const TArray<FCameraSensor>& FCameraSensors::All()\n"
        "{\n"
        "    static const TArray<FCameraSensor> Data = {\n"
        + "\n".join(lines) + "\n"
        "    };\n"
        "    return Data;\n"
        "}\n"
    )

    CPP_PATH.write_text(cpp_contents, encoding="utf-8")
    print(f"Wrote {CPP_PATH.name} ({len(rows)} sensors)")


if __name__ == "__main__":
    main()