// Copyright Hollywood Camera Work
// Generated by CameraSensorDatabase -> convert_to_cpp.py — do not edit by hand.

#pragma once

#include "CoreMinimal.h"

struct FCameraSensor
{
    FString Manufacturer;
    FString Camera;
    FString Format;
    float Width;
    float Height;
};

class FCameraSensors
{
    public: static const TArray<FCameraSensor>& All();
};
